# Generated by Django 5.0.2 on 2024-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(choices=[(1, 'چرخ خیاطی'), (2, 'اتو پرس'), (3, 'اتو مخزن دار')], default=0, verbose_name='نوع دستگاه')),
                ('model', models.CharField(max_length=255, verbose_name='مدل')),
                ('serial', models.CharField(max_length=255, verbose_name='سریال')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید')),
            ],
        ),
    ]
