# Generated by Django 5.0.2 on 2024-09-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_delete_level_1'),
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_1',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_submissions', to='authenticate.user'),
        ),
    ]
