# Generated by Django 5.0.2 on 2024-09-23 14:27

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_remove_user_first_name_remove_user_last_name_and_more'),
        ('warranty', '0002_level_1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_1',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='level_1',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.CreateModel(
            name='Level_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt', models.ImageField(upload_to='data/receipts/', verbose_name='تصویر پرداختی')),
                ('serial_payment', models.CharField(max_length=255, verbose_name='سریال پرداخت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید')),
                ('level1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warranty.level_1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_submissions', to='authenticate.user', verbose_name='کاربر')),
            ],
        ),
    ]
