# Generated by Django 5.0.2 on 2024-09-23 14:41

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_level_1_date_level_1_price_level_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_1',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
