# Generated by Django 5.0.2 on 2024-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0005_alter_level_1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_1',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
