# Generated by Django 5.0.2 on 2024-09-24 02:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_level_1_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_1',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع گارانتی'),
        ),
        migrations.AlterField(
            model_name='level_1',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان گارانتی'),
        ),
    ]
