# Generated by Django 5.0.2 on 2024-09-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0010_level_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level_1',
            options={'verbose_name': 'گارانتی', 'verbose_name_plural': 'گارانتی ها'},
        ),
        migrations.AlterModelOptions(
            name='level_2',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداختی ها'},
        ),
        migrations.AlterModelOptions(
            name='level_3',
            options={'verbose_name': 'تایید نهایی', 'verbose_name_plural': 'تایید نهایی'},
        ),
        migrations.AlterField(
            model_name='level_2',
            name='level1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warranty.level_1', verbose_name='گارانتی'),
        ),
        migrations.AlterField(
            model_name='level_3',
            name='level1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warranty.level_1', verbose_name='گارانتی'),
        ),
        migrations.AlterField(
            model_name='level_3',
            name='level2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warranty.level_2', verbose_name='پرداختی ها'),
        ),
    ]
