# Generated by Django 5.0.2 on 2024-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0012_remove_level_3_final_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_1',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام برند'),
        ),
    ]
