# Generated by Django 5.0.2 on 2024-10-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0014_level_1_pic_machine_level_1_pic_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_2',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد'),
        ),
    ]
