# Generated by Django 5.0.2 on 2024-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0015_level_2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_2',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='کد'),
        ),
    ]
