# Generated by Django 5.0.2 on 2024-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_1',
            name='model',
            field=models.CharField(max_length=255, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='level_1',
            name='serial',
            field=models.CharField(max_length=255, verbose_name='سریال'),
        ),
        migrations.AlterField(
            model_name='level_1',
            name='types',
            field=models.IntegerField(choices=[(1, 'چرخ خیاطی'), (2, 'اتو پرس'), (3, 'اتو مخزن دار')], default=0, verbose_name='نوع دستگاه'),
        ),
    ]
