# Generated by Django 5.0.2 on 2024-09-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_alter_level_1_model_alter_level_1_serial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='level_1',
        ),
    ]
