# Generated by Django 5.0.2 on 2024-09-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
