# Generated by Django 5.0.2 on 2024-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_user_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند'),
        ),
    ]
