# Generated by Django 5.0.2 on 2024-10-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='کد')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='اختصاص داده شده')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.code', verbose_name='کد اختصاص داده شده'),
        ),
    ]
