# Generated by Django 5.0.2 on 2024-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_code_user_assigned_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_code', models.IntegerField(verbose_name='تعداد کدها')),
            ],
        ),
    ]
