# Generated by Django 5.0.2 on 2024-10-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_codegeneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_code',
        ),
        migrations.DeleteModel(
            name='CodeGeneration',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
