# Generated by Django 5.0.2 on 2024-10-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_uniquecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueCode',
        ),
    ]
