# Generated by Django 5.0.2 on 2024-10-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_delete_uniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
