# Generated by Django 5.0.2 on 2024-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0023_user_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_codes', models.IntegerField(default=1, verbose_name='Number of Codes')),
            ],
        ),
    ]
