# Generated by Django 5.0.2 on 2024-10-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0025_generatedcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.generatedcode'),
        ),
    ]
