# Generated by Django 5.0.2 on 2024-10-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_remove_user_unique_code_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcode',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
