# Generated by Django 5.0.2 on 2024-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0028_alter_codegenerator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیر فعال'),
        ),
    ]
